import type { Metadata } from "next";
import { Inter, Noto_Sans_JP, Caveat } from "next/font/google";
import "./globals.css";
//Components
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import NavbarSecundario from "./components/NavbarSecundario";
import LoadingBarScroll from "./components/LoadingBarScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Importar fuentes
const inter = Inter({ subsets: ["latin"] });

const caveat = Caveat({
  weight: "500",
  subsets: ["latin"],
  variable: "--font-caveat",
});

const noto_sans_jp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: "900",
  variable: "--font-noto-sans-jp",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${noto_sans_jp.variable}  ${inter.className} ${caveat.variable}  bg-Neutral-950 max-w-[1500px] mx-auto `}
      >
          <LoadingBarScroll />
          <Navbar />
          <NavbarSecundario />
          {children}
          <Footer />
      </body>
    </html>
  );
}
